### compute matrix rank example

In [107]:
import numpy as np

A=np.random.randn(3,6)

print("Matrix A:")
print(A)
r=np.linalg.matrix_rank(A)
print("Matrix A Rank:",r)
B=np.random.randint(0, 2, (3, 6))
print("Matrix B:")
print(B)
print("Matrix B Rank:", np.linalg.matrix_rank(B))


Matrix A:
[[ 0.03309321 -0.73053498 -0.11242559 -1.59675967  0.59187436 -0.2912448 ]
 [ 0.04731685 -1.42797335  0.44263403 -0.20064226  0.61968811 -1.47594401]
 [ 0.60835936  1.38213056 -0.21425853  0.16726463 -1.71067958 -0.05281557]]
Matrix A Rank: 3
Matrix B:
[[1 1 0 0 0 1]
 [0 0 0 0 1 1]
 [1 1 1 1 0 0]]
Matrix B Rank: 3


In [119]:
s=np.random.randn()
M=np.random.randn(3, 5)
print("Scalar s:", s)
print("Matrix M:")
print(M)
r1=np.linalg.matrix_rank(M)
r2=np.linalg.matrix_rank(s*M)
print(r1, r2)

Scalar s: -0.6499585535602331
Matrix M:
[[ 0.31353241 -0.10482263 -0.08062153 -0.24291926  0.34511971]
 [ 1.46659188  1.25881423  0.49649865 -1.4333367   1.29612081]
 [-0.3847548  -0.92059513  0.43898865  0.32980211  1.1456086 ]]
3 3
