In [5]:
import numpy as np

#z=np.complex(3,4)
z=complex(3, 4)
print(z)
z2=complex(5, 6)
print(z2)

Z=np.zeros(2, dtype=complex )
print("Z = ",Z)
Z[0]=3+4j
Z[1]=z2
print(Z)

(3+4j)
(5+6j)
Z =  [0.+0.j 0.+0.j]
[3.+4.j 5.+6.j]


In [12]:
r=np.random.randint(-3, 3,size=3)
print("real part is ",r)
i=np.random.randint(-3, 3,size=3)
print("imaginary part is ",i)
Z=r + 1j*i
print(Z)
print(Z.dtype)
print(Z.real)
print(Z.imag)   
print(Z.conjugate())
ZZ_C=(Z*Z.conjugate())
print(ZZ_C)
print(ZZ_C.real)
print(ZZ_C.imag)


real part is  [-3  0 -3]
imaginary part is  [-3 -2  2]
[-3.-3.j  0.-2.j -3.+2.j]
complex128
[-3.  0. -3.]
[-3. -2.  2.]
[-3.+3.j  0.+2.j -3.-2.j]
[18.+0.j  4.+0.j 13.+0.j]
[18.  4. 13.]
[0. 0. 0.]


In [30]:
v=np.array([complex(0,0),complex(0,1)])
print(v)
print(np.dot(v, v))
print(np.dot(v,v.T))
print(np.dot(v,v.conjugate()))
print(np.dot(v.T,v.conjugate()))
print(np.vdot(v, v))

[0.+0.j 0.+1.j]
(-1+0j)
(-1+0j)
(1+0j)
(1+0j)
(1+0j)


In [ ]:
a=3+4j
print(a)
b=-6*(-5-1j)
print(b)
c=1j #파이썬에서는 j만 사용하면 이것이 그저 string으로 여겨지고, 이것이 허수를 나타내는 것인지 알수 없으므로 1j라고 써야 허수임을 나타낸다.
d=17
print(c)
print(d)

print(a.conjugate())
print(b.conjugate())
print(c.conjugate())
print(d.conjugate())

(3+4j)
(30+6j)
1j
17
(3-4j)
(30-6j)
-1j
17


In [20]:
z=complex(3,6)
print(z)
w=complex(-2,-5)
print(w)

(3+6j)
(-2-5j)


In [24]:
a=2*z+w*z
b=w*(z+z.conjugate())
c=5*z+6*w
d=5*z+6*w.conjugate()
e=((w+2)*z)/w
ja=(w+2)*z
ja2=ja*w.conjugate()
mo=w*w.conjugate()


print(a)
print(b)
print(c)
print(d)
print(e)
print(ja)
print(ja2)
print(mo)

(30-15j)
(-12-30j)
(3+0j)
(3+60j)
(0.5172413793103449+6.206896551724138j)
(30-15j)
(15+180j)
(29+0j)


In [31]:
# Define two complex vectors
v1 = np.array([1 + 2j, 3 + 4j])
v2 = np.array([5 + 6j, 7 + 8j])

# Compute the Hermitian dot product
hermitian_dot_product = np.vdot(v1, v2)  # vdot automatically conjugates the first vector
print("Hermitian Dot Product (Vectors):", hermitian_dot_product)

Hermitian Dot Product (Vectors): (70-8j)


In [32]:
m1 = np.array([[1 + 2j, 3 + 4j], [5 + 6j, 7 + 8j]])
m2 = np.array([[9 + 10j, 11 + 12j], [13 + 14j, 15 + 16j]])

# Compute the Hermitian dot product
hermitian_dot_product = np.vdot(m1, m2)  # vdot automatically conjugates the first vector
print("Hermitian Dot Product (Matrix):", hermitian_dot_product)

Hermitian Dot Product (Matrix): (492-32j)


In [39]:
z=np.array([[1],[3j],[4-2j]])
w=np.array([[1j],[1-1j],[0]])

print(z)
print(w)

a=np.vdot(z,(z+w))
b=(np.vdot(z,z))/(np.vdot(w,w))
c=2*z+(w*z)

up=np.vdot(z,z)
do=np.vdot(w,w)
result=up/do
print(up)
print(do)
print(result)


print("a = ",a)
print("b = ",b)
print("c = \n",c)

[[1.+0.j]
 [0.+3.j]
 [4.-2.j]]
[[0.+1.j]
 [1.-1.j]
 [0.+0.j]]
(30+0j)
(3+0j)
(10+0j)
a =  (27-2j)
b =  (10+0j)
c = 
 [[2.+1.j]
 [3.+9.j]
 [8.-4.j]]


In [16]:
w=2+5j
#print(w)
z=0-1j
#print(z)
d=np.array([[4],[2+2j],[0-4j]])
#print(d)
R=np.array([[3,4,0+1j],[0-2j,0,0],[4,1,1]])
#print(R)

# print("a = ",np.dot(w,d))
# print("b = ",np.dot(np.dot(d.conj().T,w),d))
# print("c = ",np.dot(R,d))
# print("d = ",np.dot(np.dot(R.conj().T,R),d))

print("e = ",np.dot(w,z))
print("f = ", np.dot(w,z.conjugate()))
#print("g = ",np.dot(np.dot(w,d),R))
print("h = ",np.dot(np.dot(w,d.conj().T),R))


e =  (5-2j)
f =  (-5+2j)
h =  [[-44.+64.j  12.+88.j -40.+16.j]]


In [19]:
U=0.5*np.array([[1+1j,1-1j],[1-1j,1+1j]])
#print(U)
U_H=np.matrix(U).H
print(U_H)
print(np.dot(U.conj().T,U))
print(U@U_H)

[[0.5-0.5j 0.5+0.5j]
 [0.5+0.5j 0.5-0.5j]]
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [21]:
r=np.random.randn(3,3)
i=np.random.randn(3,3)
A=np.matrix(r+i*1j)
#print(A)
A1=A+A.H
A2=A@A.H
print(A1-A1.H)
print(A2-A2.H) 

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]
[[0.-5.78420305e-17j 0.+0.00000000e+00j 0.+3.12250226e-16j]
 [0.+0.00000000e+00j 0.+6.03103435e-16j 0.-4.44089210e-16j]
 [0.+3.12250226e-16j 0.-4.44089210e-16j 0.-4.11209298e-17j]]
