In [9]:
import numpy as np
a=np.random.randn()
b=np.random.randn()
a*b-b*a
# This code generates two random numbers, a and b, using a normal distribution.
#v=np.array([a*10, b])
#v

0.0

In [13]:
v=np.array([[4,5,6]])
w=np.array([[10,20,30]]).T
v+w

array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

The Vector Dot product
=inner product

In [15]:
v

array([[4, 5, 6]])

In [16]:
w

array([[10],
       [20],
       [30]])

element-wise multiplcation and sum
same dimensionality


In [17]:
v=np.array([1,2,3,4])
w=np.array([5,6,7,8])
np.dot(v, w)

np.int64(70)

In [18]:
s=10
np.dot(s*v, w)

np.int64(700)

In [20]:
v*w

array([ 5, 12, 21, 32])

w.T

In [21]:
w.T

array([5, 6, 7, 8])

In [22]:
np.dot(v, w.T)

np.int64(70)

In [23]:
x=np.array([[5], [6], [7], [8]])
x

array([[5],
       [6],
       [7],
       [8]])

In [25]:
z=np.dot(v, x)
z

array([70])

In [1]:
import numpy as np
print(np.__version__)

2.3.0
