In [4]:
import numpy as np
import sympy as sp
from scipy import linalg

# 예시: 3x3 정방행렬
A = np.array([[2, 1, 3],
              [1, 0, 2],
              [4, 1, 8]], dtype=float)



print("행렬 A:")
print(A)

# ------------------------------
# 1. NumPy를 이용한 determinant
# ------------------------------
det_numpy = np.linalg.det(A)
print("\n[NumPy] determinant =", det_numpy)

# ------------------------------
# 2. SymPy를 이용한 determinant
# ------------------------------
A_sym = sp.Matrix(A)
det_sympy = A_sym.det()
print("[SymPy] determinant =", det_sympy)

# ------------------------------
# 3. SciPy를 이용한 determinant
# ------------------------------
det_scipy = linalg.det(A)
print("[SciPy] determinant =", det_scipy)

행렬 A:
[[2. 1. 3.]
 [1. 0. 2.]
 [4. 1. 8.]]

[NumPy] determinant = -1.0
[SymPy] determinant = -1.00000000000000
[SciPy] determinant = -1.0


In [5]:
A1 = np.array([[1, 1, 2],
               [2, 2, 1],   
                [4, 3, 0]], dtype=float)
print("행렬 A1:")
print(A1)

# ------------------------------
# 1. NumPy를 이용한 determinant
# ------------------------------
det_numpy = np.linalg.det(A1)
print("\n[NumPy] determinant =", det_numpy)

# ------------------------------
# 2. SymPy를 이용한 determinant
# ------------------------------
A_sym = sp.Matrix(A1)
det_sympy = A_sym.det()
print("[SymPy] determinant =", det_sympy)

# ------------------------------
# 3. SciPy를 이용한 determinant
# ------------------------------
det_scipy = linalg.det(A1)
print("[SciPy] determinant =", det_scipy)

행렬 A1:
[[1. 1. 2.]
 [2. 2. 1.]
 [4. 3. 0.]]

[NumPy] determinant = -2.9999999999999996
[SymPy] determinant = -3.00000000000000
[SciPy] determinant = -3.0


In [6]:
A2 = np.array([[1, 1, 2],
               [4, 3,0],   
                [2, 2, 1]], dtype=float)
print("행렬 A2:")
print(A2)
det_numpy = np.linalg.det(A2)
print("\n[NumPy] determinant =", det_numpy)


A_sym = sp.Matrix(A2)
det_sympy = A_sym.det()
print("[SymPy] determinant =", det_sympy)

# ------------------------------
# 3. SciPy를 이용한 determinant
# ------------------------------
det_scipy = linalg.det(A2)
print("[SciPy] determinant =", det_scipy)

행렬 A2:
[[1. 1. 2.]
 [4. 3. 0.]
 [2. 2. 1.]]

[NumPy] determinant = 2.9999999999999996
[SymPy] determinant = 3.00000000000000
[SciPy] determinant = 3.0


In [7]:
A3 = np.array([[1, 2, 4],
               [1, 2,3],   
                [2, 1, 0]], dtype=float)
print("행렬 A3:")
print(A3)
det_numpy = np.linalg.det(A3)
print("\n[NumPy] determinant =", det_numpy)


A_sym = sp.Matrix(A3)
det_sympy = A_sym.det()
print("[SymPy] determinant =", det_sympy)

# ------------------------------
# 3. SciPy를 이용한 determinant
# ------------------------------
det_scipy = linalg.det(A3)
print("[SciPy] determinant =", det_scipy)

행렬 A3:
[[1. 2. 4.]
 [1. 2. 3.]
 [2. 1. 0.]]

[NumPy] determinant = -2.9999999999999996
[SymPy] determinant = -3.00000000000000
[SciPy] determinant = -3.0


In [8]:
A4 = np.array([[1, -2, 3],
               [-4, 5,-6],   
                [7, -8, 9]], dtype=float)
print("행렬 A4:")
print(A4)
det_numpy = np.linalg.det(A4)
print("\n[NumPy] determinant =", det_numpy)


A_sym = sp.Matrix(A4)
det_sympy = A_sym.det()
print("[SymPy] determinant =", det_sympy)

# ------------------------------
# 3. SciPy를 이용한 determinant
# ------------------------------
det_scipy = linalg.det(A4)
print("[SciPy] determinant =", det_scipy)

행렬 A4:
[[ 1. -2.  3.]
 [-4.  5. -6.]
 [ 7. -8.  9.]]

[NumPy] determinant = 0.0
[SymPy] determinant = 0
[SciPy] determinant = 0.0
