In [5]:
import numpy as np
from sympy import Matrix, latex
from IPython.display import display, Math
import time

def show_matrix_latex(A, step_desc=""):
    """행렬을 LaTeX 표 형식으로 출력 (KaTeX 오류 방지)"""
    M = Matrix(A)
    latex_str = r"\left[ " + latex(M) + r" \right]"
    if step_desc:
        display(Math(r"\text{" + step_desc + r"}"))
    display(Math(latex_str))
    time.sleep(0.8)  # 단계별로 잠깐 대기

def row_reduction_steps_latex(A):
    """Gaussian elimination을 LaTeX 표 형식으로 단계별 표시"""
    A = A.astype(float)
    rows, cols = A.shape
    pivot_row = 0
    
    show_matrix_latex(A, "Initial Matrix")
    
    for pivot_col in range(cols):
        # 1. 피벗 찾기
        max_row = np.argmax(np.abs(A[pivot_row:rows, pivot_col])) + pivot_row
        if A[max_row, pivot_col] == 0:
            continue
        
        # 2. 행 교환
        if max_row != pivot_row:
            A[[pivot_row, max_row]] = A[[max_row, pivot_row]]
            show_matrix_latex(A, f"Swap row {pivot_row+1} with row {max_row+1}")
        
        # 3. 피벗을 1로 만들기
        pivot_val = A[pivot_row, pivot_col]
        A[pivot_row] = A[pivot_row] / pivot_val
        show_matrix_latex(A, f"Make pivot in row {pivot_row+1} a 1")
        
        # 4. 피벗 아래를 0으로 만들기
        for r in range(pivot_row+1, rows):
            if A[r, pivot_col] != 0:
                factor = A[r, pivot_col]
                A[r] = A[r] - factor * A[pivot_row]
                show_matrix_latex(A, f"Eliminate entry in row {r+1}, col {pivot_col+1}")
        
        pivot_row += 1
        if pivot_row == rows:
            break
    
    show_matrix_latex(A, "Final Echelon Form")
    return A

# 예시 행렬
A = np.array([
    [2, 4, -2],
    [4, 9, -3],
    [-2, -3, 7],
    [0, -2, 6]
], dtype=float)

row_reduction_steps_latex(A)




<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

array([[ 1.  ,  2.25, -0.75],
       [-0.  ,  1.  , -3.  ],
       [ 0.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.  ]])

In [4]:
B = np.array([
    [3, 3, 5],
    [-4, 4, 0],
    [5, 1, 5],
    [6, 2, 1]
], dtype=float)

In [5]:
row_reduction_steps_latex(B)

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

array([[1.        , 0.33333333, 0.16666667],
       [0.        , 1.        , 0.125     ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        ]])

In [2]:
import numpy as np
import sympy as sym

A=np.random.randn(2,4)
print(sym.Matrix(A).rref()) # Reduced Row Echelon Form (RREF) of A
print(sym.Matrix(A).rref()[0]) # RREF matrix
print(sym.Matrix(A).rref()[1]) # Pivot columns of RREF matrix


(Matrix([
[1, 0, -0.745165781612625, -0.24179086331203],
[0, 1,  0.416464625350309, -1.11430523389072]]), (0, 1))
Matrix([[1, 0, -0.745165781612625, -0.241790863312030], [0, 1, 0.416464625350309, -1.11430523389072]])
(0, 1)


In [3]:
a=np.array([[4,8,4,3],[0,1,8,0],[2,7,0,8]])
print(sym.Matrix(a).rref()) # Reduced Row Echelon Form (RREF) of a

(Matrix([
[1, 0, 0,   -3],
[0, 1, 0,    2],
[0, 0, 1, -1/4]]), (0, 1, 2))


In [4]:
b=np.array([[4,0,2],[8,1,7],[4,8,0],[3,0,8]])
print(sym.Matrix(b).rref()) # Reduced Row Echelon Form (RREF) of b

(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1],
[0, 0, 0]]), (0, 1, 2))


In [5]:
c=np.array([[13,7,4,7],[5,3,2,3],[2,1,1,1]])
print(sym.Matrix(c).rref()) # Reduced Row Echelon Form (RREF) of c

(Matrix([
[1, 0, 0, 0],
[0, 1, 0, 1],
[0, 0, 1, 0]]), (0, 1, 2))


In [6]:
a1= np.array([[3, 10, 62], [-1,3,11]])
print(sym.Matrix(a1).rref()) # Reduced Row Echelon Form (RREF) of a1

(Matrix([
[1, 0, 4],
[0, 1, 5]]), (0, 1))


In [7]:
b1= np.array([[3, 10, 11.5], [-1, 3,-1.3]])
print(sym.Matrix(b1).rref()) # Reduced Row Echelon Form (RREF) of b1

(Matrix([
[1, 0, 2.5],
[0, 1, 0.4]]), (0, 1))


In [8]:
c1= np.array([[4,-6,3,1], [1,2,5, 8], [1,3,-4,0]])
print(sym.Matrix(c1).rref()) # Reduced Row Echelon Form (RREF) of c1

(Matrix([
[1, 0, 0, 1],
[0, 1, 0, 1],
[0, 0, 1, 1]]), (0, 1, 2))


In [1]:
import sympy as sp

# 4x4 행렬 예시
A = sp.Matrix([
    [2, 4, -2, 2],
    [4, 9, -3, 8],
    [-2, -3, 7, 10],
    [2, 2, 4, 6]
])

# Row Echelon Form 구하기
A_echelon = A.echelon_form()

print("원래 행렬:")
sp.pprint(A)

print("\nRow Echelon Form:")
sp.pprint(A_echelon)

원래 행렬:
⎡2   4   -2  2 ⎤
⎢              ⎥
⎢4   9   -3  8 ⎥
⎢              ⎥
⎢-2  -3  7   10⎥
⎢              ⎥
⎣2   2   4   6 ⎦

Row Echelon Form:
⎡2  4  -2   2  ⎤
⎢              ⎥
⎢0  2  2    8  ⎥
⎢              ⎥
⎢0  0  16   32 ⎥
⎢              ⎥
⎣0  0  0   -256⎦


In [2]:
A1 = sp.Matrix([
    [2, 0, -1, 1],
    [1, -2, -2, 5],
    [-3, 5, -4, -1],
    [0, -3, -1, -3]
])

A1_echelon = A1.echelon_form()

print("원래 행렬:")
sp.pprint(A1)

print("\nRow Echelon Form:")
sp.pprint(A1_echelon)

원래 행렬:
⎡2   0   -1  1 ⎤
⎢              ⎥
⎢1   -2  -2  5 ⎥
⎢              ⎥
⎢-3  5   -4  -1⎥
⎢              ⎥
⎣0   -3  -1  -3⎦

Row Echelon Form:
⎡2  0   -1   1  ⎤
⎢               ⎥
⎢0  -4  -3   9  ⎥
⎢               ⎥
⎢0  0   74  -94 ⎥
⎢               ⎥
⎣0  0   0   2416⎦


In [3]:
B1 = sp.Matrix([
    [2, 1, 3, -1],
    [-5, -6, -5, 3],
    [-3, -4, -3,2],
    [-1, -2, -1, 1]
])

B1_echelon = B1.echelon_form()

print("원래 행렬:")
sp.pprint(B1)

print("\nRow Echelon Form:")
sp.pprint(B1_echelon)

원래 행렬:
⎡2   1   3   -1⎤
⎢              ⎥
⎢-5  -6  -5  3 ⎥
⎢              ⎥
⎢-3  -4  -3  2 ⎥
⎢              ⎥
⎣-1  -2  -1  1 ⎦

Row Echelon Form:
⎡2  1   3  -1⎤
⎢            ⎥
⎢0  -7  5  1 ⎥
⎢            ⎥
⎢0  0   4  -2⎥
⎢            ⎥
⎣0  0   0  0 ⎦


In [6]:
AA=np.array([[2,0,-3],[3,1,4],[1,0,-1]])
xx=[2,3,4]
bb=A@xx
print("Ax = b 형태로 표현:")
print("A:", AA)
print("x:", xx) 
print("b:", bb)



Ax = b 형태로 표현:
A: [[ 2  0 -3]
 [ 3  1  4]
 [ 1  0 -1]]
x: [2, 3, 4]
b: [ 8. 23. 15. 18.]


In [7]:
import numpy as np
import sympy as sym

AAA=np.random.randn(3,6)
print("Random 3x6 Matrix:")
print(sym.Matrix(AAA).rref()[0])  # Reduced Row Echelon Form (RREF

Random 3x6 Matrix:
Matrix([[1, 0, 0, 1.78239489770909, -4.03992999919581, -5.42556488190258], [0, 1, 0, -1.29294813850234, 3.56624685465403, 5.14068367952828], [0, 0, 1, -2.69207176706173, 5.56438790940331, 7.94238163693468]])


In [8]:
from sympy.interactive.printing import init_printing
init_printing(use_unicode=False)
from sympy.matrices import Matrix,eye,zeros,ones,diag, GramSchmidt
# LaTeX 출력 초기화

M=Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]);M

[1  2  3]
[       ]
[4  5  6]
[       ]
[7  8  9]