In [1]:
import numpy as np

u=np.array([[2],[4],[1]])
print("Column Vector u:\n", u)
u_T=u.T
print("Row Vector u_T:\n", u_T)
#print("Dot product of u and u_T:", np.dot(u, u_T))
v=np.array([[3],[5],[0],[2]])
print("Column Vector v:\n", v)
v_T=v.T
print("Row Vector v_T:\n", v_T)
w=np.array([[1],[0],[1],[5]])
print("Column Vector w:\n", w)
w_T=w.T
print("Row Vector w_T:\n", w_T)
A=np.array([[-1, -2,-6,-6],[1,-1,0,-2],[-1,0,-1,-4]])
print("Matrix A:\n", A)
A_T=A.T
print("Transpose of Matrix A:\n", A_T)
#a=w*u.T
#print("Vector a:", a)

Column Vector u:
 [[2]
 [4]
 [1]]
Row Vector u_T:
 [[2 4 1]]
Column Vector v:
 [[3]
 [5]
 [0]
 [2]]
Row Vector v_T:
 [[3 5 0 2]]
Column Vector w:
 [[1]
 [0]
 [1]
 [5]]
Row Vector w_T:
 [[1 0 1 5]]
Matrix A:
 [[-1 -2 -6 -6]
 [ 1 -1  0 -2]
 [-1  0 -1 -4]]
Transpose of Matrix A:
 [[-1  1 -1]
 [-2 -1  0]
 [-6  0 -1]
 [-6 -2 -4]]


In [4]:
# a=w*u_T+A # 모양이 맞지 않음
b=w*u_T+A_T
print("Vector b:\n", b)

Vector b:
 [[ 1  5  0]
 [-2 -1  0]
 [-4  4  0]
 [ 4 18  1]]


In [6]:
c=u*v_T-A
print("Vector c:\n", c)

Vector c:
 [[ 7 12  6 10]
 [11 21  0 10]
 [ 4  5  1  6]]


In [9]:
#d=v*w_T-A
#print("Vector d:\n", d)
#e=v*w_T+A_T
##print("Vector e:\n", e)

In [10]:
A=np.array([[2, 4,3],[0,1,3]])
print("Updated Matrix A:\n", A)
A_T=A.T
print("Transpose of Updated Matrix A:\n", A_T)
B=np.array([[-2,1, 3],[6,-7,7]])
print("Matrix B:\n", B)
B_T=B.T
print("Transpose of Matrix B:\n", B_T)
C=np.array([[0, -6],[-3,-2],[-2,7]] )
print("Matrix C:\n", C)
C_T=C.T 
print("Transpose of Matrix C:\n", C_T)
D=np.array([[1, 2],[3,4],[2,4]])
print("Matrix D:\n", D)
D_T=D.T 
print("Transpose of Matrix D:\n", D_T)


Updated Matrix A:
 [[2 4 3]
 [0 1 3]]
Transpose of Updated Matrix A:
 [[2 0]
 [4 1]
 [3 3]]
Matrix B:
 [[-2  1  3]
 [ 6 -7  7]]
Transpose of Matrix B:
 [[-2  6]
 [ 1 -7]
 [ 3  7]]
Matrix C:
 [[ 0 -6]
 [-3 -2]
 [-2  7]]
Transpose of Matrix C:
 [[ 0 -3 -2]
 [-6 -2  7]]
Matrix D:
 [[1 2]
 [3 4]
 [2 4]]
Transpose of Matrix D:
 [[1 3 2]
 [2 4 4]]


In [11]:
a=A+3*B
print("Vector a:\n", a)

Vector a:
 [[ -4   7  12]
 [ 18 -20  24]]


In [14]:
#b=A+C
#print("Vector b:\n", b)

c=C-D
print("Vector c:\n", c)

Vector c:
 [[-1 -8]
 [-6 -6]
 [-4  3]]


In [15]:
d=D+C
print("Vector d:\n", d)

Vector d:
 [[ 1 -4]
 [ 0  2]
 [ 0 11]]


In [16]:
e=A_T+D
print("Vector e:\n", e)

Vector e:
 [[3 2]
 [7 5]
 [5 7]]


In [17]:
f=(A+B).T+2*C
print("Vector f:\n", f)

Vector f:
 [[  0  -6]
 [ -1 -10]
 [  2  24]]


In [18]:
g=3*A+(B_T+C).T
print("Vector g:\n", g)

Vector g:
 [[ 4 10 10]
 [ 0 -6 23]]


In [23]:
#h=-4*(A_T+C).T+D
#print("Vector h:\n", h)