In [1]:
import numpy as np
from scipy.linalg import lu
A= np.array([[1, 2, 2,4], [2,0, 3, 2], [8, 0, 4,0]])
P,L,U=lu(A)
print("Matrix P:")
print(P)
print("Matrix L:")
print(L)
print("Matrix U:")
print(U)
print("Product of P, L, and U:")
print(np.dot(P, np.dot(L, U)))


Matrix P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Matrix L:
[[1.    0.    0.   ]
 [0.125 1.    0.   ]
 [0.25  0.    1.   ]]
Matrix U:
[[8.  0.  4.  0. ]
 [0.  2.  1.5 4. ]
 [0.  0.  2.  2. ]]
Product of P, L, and U:
[[1. 2. 2. 4.]
 [2. 0. 3. 2.]
 [8. 0. 4. 0.]]


In [2]:
import numpy as np
a=np.asmatrix('[1,2;3,4]')
print(a)
print(a.T)
print(a.I)  # Inverse of the matrix

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


This is **Bold**.

This is _italic_ .

This is also *italic*.

This is **_bold and itallic_**

This is _italic_


Using two asterisks **this text is bold**.  
Two underscores __work as well__.  
Let's make it *italic now*.  
You guessed it, _one underscore is also enough_.  
Can we combine **_both of that_?** Absolutely.
What if I want to ~~strikethrough~~?

> This is a blockquote.
> Want to write on a new line with space between?
>
> > And nested? No problem at all.
> >
> > > PS. you can **style** your text _as you want_.