In [3]:
import numpy as np
from scipy.linalg import lu
A= np.array([[1, 2, 2,4], [2,0, 3, 2], [8, 0, 4,0]])
P,L,U=lu(A)
print("Matrix P:")
print(P)
print("Matrix L:")
print(L)
print("Matrix U:")
print(U)
print("Product of P, L, and U:")
print(np.dot(P, np.dot(L, U)))


Matrix P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Matrix L:
[[1.    0.    0.   ]
 [0.125 1.    0.   ]
 [0.25  0.    1.   ]]
Matrix U:
[[8.  0.  4.  0. ]
 [0.  2.  1.5 4. ]
 [0.  0.  2.  2. ]]
Product of P, L, and U:
[[1. 2. 2. 4.]
 [2. 0. 3. 2.]
 [8. 0. 4. 0.]]


In [3]:
import numpy as np
a=np.asmatrix('[1,2;3,4]')
print(a)
print(a.T)
print(a.I)  # Inverse of the matrix

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
