임의로 데이터를 만들어 대학생 10명의 성적을 가중 평균한 값을 구해 보려고 합니다.
퀴즈(20%), 중간고사(30%), 기말고사(50%)

In [2]:
import numpy as np

# 대학생 10명의 성적을 임의로 생성 (0~100 사이)
np.random.seed(42)  # 재현성을 위해 시드 고정
quiz_scores = np.random.randint(60, 100, size=10)       # 퀴즈 점수
midterm_scores = np.random.randint(50, 100, size=10)    # 중간고사 점수
final_scores = np.random.randint(40, 100, size=10)      # 기말고사 점수



In [3]:
quiz_scores


array([98, 88, 74, 67, 80, 98, 78, 82, 70, 70], dtype=int32)

In [6]:
midterm_scores

array([73, 85, 89, 73, 52, 71, 51, 73, 93, 79], dtype=int32)

In [7]:
final_scores

array([77, 41, 99, 60, 72, 51, 97, 61, 83, 64], dtype=int32)

In [8]:
# 가중치 설정
weights = np.array([0.2, 0.3, 0.5])  # 퀴즈 20%, 중간 30%, 기말 50%

# 학생별 성적을 하나의 배열로 결합
scores = np.vstack((quiz_scores, midterm_scores, final_scores)).T

# 학생별 최종 성적 계산 (가중 평균)
final_grades = np.average(scores, axis=1, weights=weights)

# 결과 출력
for i, grade in enumerate(final_grades, start=1):
    print(f"학생 {i} 최종 성적: {grade:.2f}")

# 전체 평균 성적
print("\n전체 평균 성적:", np.mean(final_grades))


학생 1 최종 성적: 80.00
학생 2 최종 성적: 63.60
학생 3 최종 성적: 91.00
학생 4 최종 성적: 65.30
학생 5 최종 성적: 67.60
학생 6 최종 성적: 66.40
학생 7 최종 성적: 79.40
학생 8 최종 성적: 68.80
학생 9 최종 성적: 83.40
학생 10 최종 성적: 69.70

전체 평균 성적: 73.52
