# 354 페이지 코드 쏠루션

In [3]:
import numpy as np

m=4
A=np.random.randn(m,m)
M=np.zeros((m,m))
G=np.zeros((m,m))

for i in range(m):
    for j in range(m):
        rows=[True]*m
        rows[i]=False
        
        cols=[True]*m
        cols[j]=False
        
        M[i,j]=np.linalg.det(A[rows,:][:,cols])
        
        G[i,j]=(-1)**(i+j)
        
C=M*G

Ainv=C.T/np.linalg.det(A)
AinvI=np.linalg.inv(A)
AinvI-Ainv
        

array([[ 0.00000000e+00, -1.11022302e-16, -5.55111512e-17,
        -2.77555756e-17],
       [-6.93889390e-17,  1.11022302e-16,  2.22044605e-16,
         5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  2.22044605e-16,
         1.11022302e-16],
       [ 0.00000000e+00,  1.11022302e-16, -2.22044605e-16,
        -5.55111512e-17]])

### row reduction augmnent 행렬을 만들어서 역행렬을 구하는 코드(코파일럿)

In [4]:
import numpy as np

def mca_inverse(A):
    """
    Compute the inverse of a matrix using the MCA (row reduction) algorithm.
    A must be a square numpy array.
    """
    n = A.shape[0]
    # Create augmented matrix [A | I]
    aug = np.hstack((A.astype(float), np.eye(n)))
    
    # Perform row reduction
    for i in range(n):
        # Pivot: make sure aug[i,i] is nonzero
        if aug[i, i] == 0:
            # Swap with a row below that has a nonzero in column i
            for j in range(i+1, n):
                if aug[j, i] != 0:
                    aug[[i, j]] = aug[[j, i]]
                    break
            else:
                raise ValueError("Matrix is singular and cannot be inverted.")
        
        # Scale row i so pivot becomes 1
        aug[i] = aug[i] / aug[i, i]
        
        # Eliminate other rows
        for j in range(n):
            if j != i:
                aug[j] = aug[j] - aug[j, i] * aug[i]
    
    # The right half is now the inverse
    return aug[:, n:]

# Example usage:
A = np.array([[1, 2, 3],
              [1, 3, 4],
              [1, 2, 5]])

A_inv = mca_inverse(A)
print("Inverse of A:")
print(A_inv)

# Verify: A * A_inv should be identity
print("Check (A * A_inv):")
print(np.dot(A, A_inv))


Inverse of A:
[[ 3.5 -2.  -0.5]
 [-0.5  1.  -0.5]
 [-0.5  0.   0.5]]
Check (A * A_inv):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### MCA 알고리즘을 코드로 짜서 역행렬 구하기

In [5]:
import sympy as sp

def inverse_by_mca(A):
    # 행렬식
    detA = A.det()
    if detA == 0:
        raise ValueError("Matrix is singular, no inverse exists.")
    
    # 소행렬 및 여인수 행렬
    n = A.shape[0]
    cofactor_matrix = sp.zeros(n)
    for i in range(n):
        for j in range(n):
            minor = A.minor(i, j)   # 소행렬식
            cofactor_matrix[i, j] = ((-1)**(i+j)) * minor
    
    # 수반행렬 (여인수 행렬의 전치)
    adjA = cofactor_matrix.T
    
    # 역행렬
    A_inv = (1/detA) * adjA
    return A_inv

# 예시: 3x3 행렬
A = sp.Matrix([[1, 2, 3],
               [1, 3, 4],
               [1, 2, 5]])

A_inv = inverse_by_mca(A)
print("Inverse of A:")
print(A_inv)

# 검산: A * A_inv = I
print("Check (A * A_inv):")
print(A * A_inv)


Inverse of A:
Matrix([[7/2, -2, -1/2], [-1/2, 1, -1/2], [-1/2, 0, 1/2]])
Check (A * A_inv):
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


### 356 페이지 슈도 인버스 구하는 것 코드

In [7]:
import numpy as np

A=np.random.randn(5,5)
Ai=np.linalg.inv(A)
Api=np.linalg.pinv(A)

Ai-Api



array([[ 2.77555756e-16, -2.22044605e-16,  5.55111512e-17,
         4.71844785e-16,  8.88178420e-16],
       [-3.88578059e-16,  8.88178420e-16, -2.77555756e-17,
        -4.44089210e-16,  1.55431223e-15],
       [ 8.88178420e-16, -1.77635684e-15,  1.11022302e-16,
         0.00000000e+00, -5.32907052e-15],
       [-4.44089210e-16,  1.99840144e-15, -1.66533454e-16,
        -1.99840144e-15, -4.44089210e-16],
       [ 8.88178420e-16, -4.44089210e-15,  3.98986399e-17,
         3.55271368e-15, -3.55271368e-15]])

In [8]:
T=np.random.randn(5,3)
Tl=np.linalg.inv(T.T@T)@T.T
Tpi=np.linalg.pinv(T)
Tl-Tpi

array([[-5.55111512e-17, -1.11022302e-16,  0.00000000e+00,
        -1.94289029e-16, -9.71445147e-17],
       [ 0.00000000e+00, -2.22044605e-16,  0.00000000e+00,
         9.71445147e-17, -2.77555756e-17],
       [-2.22044605e-16,  1.28586378e-16,  1.66533454e-16,
         1.11022302e-16,  5.55111512e-17]])