In [5]:
import numpy as np

M1=np.random.randint(1, 5, (4, 3))
M2=np.random.randint(1,4, (3, 5))
print("Matrix M1:\n", M1)
print("Matrix M2:\n", M2)
C=M1@M2
print("Matrix C:\n", C)


Matrix M1:
 [[4 1 3]
 [3 2 4]
 [2 3 3]
 [4 4 4]]
Matrix M2:
 [[3 2 1 1 1]
 [3 3 2 2 1]
 [1 2 1 3 2]]
Matrix C:
 [[18 17  9 15 11]
 [19 20 11 19 13]
 [18 19 11 17 11]
 [28 28 16 24 16]]
