In [1]:
import numpy as np

# 열 벡터 (column vector): 3x1 shape
column_vector = np.array([[1], [2], [3]])
print("Original column vector:\n", column_vector)
#print("Shape:", column_vector.shape)  # (3, 1)

# 방법 1: 전치(transpose)
row_vector_1 = column_vector.T
print("\nRow vector using transpose:\n", row_vector_1)
#print("Shape:", row_vector_1.shape)  # (1, 3)

# 방법 2: reshape 사용
row_vector_2 = column_vector.reshape(1, -1)
print("\nRow vector using reshape:\n", row_vector_2)
#print("Shape:", row_vector_2.shape)  # (1, 3)

# 방법 3: flatten 후 다시 2차원으로
row_vector_3 = column_vector.flatten().reshape(1, -1)
print("\nRow vector using flatten and reshape:\n", row_vector_3)
#print("Shape:", row_vector_3.shape)  # (1, 3)

Original column vector:
 [[1]
 [2]
 [3]]

Row vector using transpose:
 [[1 2 3]]

Row vector using reshape:
 [[1 2 3]]

Row vector using flatten and reshape:
 [[1 2 3]]
