간단한 행렬을 만들어봅니다.
그리고 이를 출력하고, 그것의 전치행렬 (Transpose)해서 출력한다.


In [2]:
import numpy as np

a= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a.T)

B=np.random.randn(2,5)
print(B)
print(B.T)
B_T=np.transpose(B)
print(B_T)  


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[-1.55910589  2.44970353  0.93938143 -0.21455739  0.58950802]
 [ 0.09909065  0.84304024  2.21914294 -1.11392098  1.54474685]]
[[-1.55910589  0.09909065]
 [ 2.44970353  0.84304024]
 [ 0.93938143  2.21914294]
 [-0.21455739 -1.11392098]
 [ 0.58950802  1.54474685]]
[[-1.55910589  0.09909065]
 [ 2.44970353  0.84304024]
 [ 0.93938143  2.21914294]
 [-0.21455739 -1.11392098]
 [ 0.58950802  1.54474685]]


아래는 생성(인공지능을 )사용해서 코드를 만들어 보고 이를 적용한후
추가해본것이다.

In [ ]:
C = np.array([[2, 4, 6], 
              [8, 10, 12], 
              [14, 16, 18]])

D = np.random.randint(1, 10, size=(3, 4))

E = np.eye(3)  # 3x3 identity matrix
print("Matrix C:\n", C)
print("\nTranspose of Matrix C:\n", C.T)

print("\nMatrix D:\n", D)
print("\nTranspose of Matrix D:\n", D.T)  

print("\nMatrix E:\n", E)  
print("\nTranspose of Matrix E:\n", E.T)

In [ ]:
# Create a 4x4 symmetric matrix
sym_matrix = np.array([[1, 2, 3, 4],
                      [2, 5, 6, 7],
                      [3, 6, 8, 9],
                      [4, 7, 9, 10]])

print("Symmetric Matrix:")
print(sym_matrix)

# Verify it's symmetric by checking if it equals its transpose
is_symmetric = np.array_equal(sym_matrix, sym_matrix.T)
print("\nIs the matrix symmetric?", is_symmetric)

In [ ]:
# Create a 5x5 skew-symmetric matrix

skew_matrix = np.array([[0, -2, 3],
                        [2, 0, -5],
                        [-3, 5, 0]])

print("Skew-symmetric Matrix:")
print(skew_matrix)

# Verify it's skew-symmetric by checking if it equals negative of its transpose
is_skew_symmetric = np.array_equal(skew_matrix, -skew_matrix.T)
print("\nIs the matrix skew-symmetric?", is_skew_symmetric)

# Show that A^T = -A
print("\nTranspose of the matrix:")
print(skew_matrix.T)
print("\nNegative of the matrix:")
print(-skew_matrix)

In [ ]:
# Create a 5x5 skew-symmetric matrix
skew_matrix_5x5 = np.array([
    [ 0, -1,  2, -3,  4],
    [ 1,  0, -5,  6, -7],
    [-2,  5,  0, -8,  9],
    [ 3, -6,  8,  0, -10],
    [-4,  7, -9, 10,  0]
])

print("5x5 Skew-symmetric Matrix:")
print(skew_matrix_5x5)

# Verify it's skew-symmetric
is_skew_symmetric_5x5 = np.array_equal(skew_matrix_5x5, -skew_matrix_5x5.T)
print("\nIs the matrix skew-symmetric?", is_skew_symmetric_5x5)

In [ ]:
# Create identity vectors of different sizes
id_vec_3 = np.eye(3, 1).flatten()  # 3x1 identity vector
id_vec_4 = np.eye(4, 1).flatten()  # 4x1 identity vector
id_vec_5 = np.eye(5, 1).flatten()  # 5x1 identity vector

print("3D Identity Vector:", id_vec_3)
print("4D Identity Vector:", id_vec_4)
print("5D Identity Vector:", id_vec_5)

In [ ]:
# Reshape the existing identity vectors into column vectors
col_vec_3 = id_vec_3.reshape(-1, 1)
col_vec_4 = id_vec_4.reshape(-1, 1)
col_vec_5 = id_vec_5.reshape(-1, 1)

# Print the column vectors
print("3D Identity Column Vector:\n", col_vec_3)
print("\n4D Identity Column Vector:\n", col_vec_4)
print("\n5D Identity Column Vector:\n", col_vec_5)

# Calculate the dot product of each vector with itself
dot_prod_3 = np.dot(id_vec_3, col_vec_3)
dot_prod_4 = np.dot(id_vec_4, col_vec_4)
dot_prod_5 = np.dot(id_vec_5, col_vec_5)

print("\nDot products with themselves:")
print("3D vector:", dot_prod_3)
print("4D vector:", dot_prod_4)
print("5D vector:", dot_prod_5)

In [ ]:
# Create identity matrices of different sizes
id_2 = np.eye(2)  # 2x2 identity matrix
id_4 = np.eye(4)  # 4x4 identity matrix
id_6 = np.eye(6)  # 6x6 identity matrix

print("2x2 Identity Matrix:\n", id_2)
print("\n4x4 Identity Matrix:\n", id_4)
print("\n6x6 Identity Matrix:\n", id_6)

In [ ]:
# Create zeros matrices of different sizes
zeros_2x3 = np.zeros((2, 3))
zeros_3x4 = np.zeros((3, 4))
zeros_4x5 = np.zeros((4, 5))

print("2x3 Zeros Matrix:\n", zeros_2x3)
print("\n3x4 Zeros Matrix:\n", zeros_3x4)
print("\n4x5 Zeros Matrix:\n", zeros_4x5)

In [ ]:
# Create square zeros matrices
zeros_3x3 = np.zeros((3, 3))
zeros_5x5 = np.zeros((5, 5))
zeros_6x6 = np.zeros((6, 6))

print("3x3 Square Zeros Matrix:\n", zeros_3x3)
print("\n5x5 Square Zeros Matrix:\n", zeros_5x5)
print("\n6x6 Square Zeros Matrix:\n", zeros_6x6)

In [ ]:

I= np.eye(4)  # 3x3 identity matrix
print("Identity Matrix I:\n", I)
O=np.ones(4)
print("Ones Vector O:\n", O)
# Create a 3x3 identity matrix
Z=np.zeros(4)
print("Zeros Vector Z:\n", Z)
zb=np.zeros((4,4))
print("Zeros Matrix zb:\n", zb)



In [ ]:
D=np.diag([1, 2, 3, 5])
# Diagonal matrix with elements 1, 2, 3, 5
print("Diagonal Matrix D:\n", D)
R=np.random.rand(3,4)
d=np.diag(R)
k=np.diag(D)
print("Random Matrix R:\n", R)
print("Diagonal of Random Matrix d:\n", d)
print("Diagonal of Matrix D:\n", k)


In [ ]:
# Create two matrices
A = np.random.randint(1, 10, size=(3, 5))  # 3x5 matrix
B = np.random.randint(1, 10, size=(3, 4))  # 3x4 matrix

# Display the original matrices
print("Matrix 1 (3x5):")
print(A)
print("\nMatrix 2 (3x4):")
print(B)

# Augment the matrices horizontally
AB = np.concatenate((A,B), axis=1)
print("\nAugmented Matrix (3x9):")
print(AB)

In [ ]:
A = np.random.randint(1,10,(5,5))
L=np.tril(A)
U=np.triu(A)# 3x5 matrix
print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)    

In [ ]:
from scipy.linalg import hankel, toeplitz
t=[1, 2, 3, 4 ]
T=toeplitz(t)
print("Toeplitz Matrix T:\n", T)
H = hankel(t, r=[2,3,4,1])
print("Hankel Matrix H:\n", H)
# Create a Hankel matrix


In [ ]:
l=0.1
I= np.eye(4) 
A=np.random.randn(4, 4)  # Random 4x4 matrix
As=A + l * I  # Add a small multiple of the identity matrix
print("Matrix A:\n", A)
print("Regularized Matrix As:\n", As)


In [ ]:
l=0.1
I= np.eye(3) 
A=np.array([[0.4,3,0],[2,1,0],[0.1,0.4,0]])  # Random 4x4 matrix
As=A + l * I  # Add a small multiple of the identity matrix
print("Matrix A:\n", A)
print("Regularized Matrix As:\n", As)

In [ ]:
l=-1
I= np.eye(3) 
A=np.array([[43,42,42],[237,746,12],[0,33,1001]])  # Random 4x4 matrix
As=A + l * I  # Add a small multiple of the identity matrix
print("Matrix A:\n", A)
print("Regularized Matrix As:\n", As)

In [ ]:
A=np.random.randn(4, 4) 
B=np.random.randint(1, 10, size=(4, 4))  # Random 4x4 matrix
print("Matrix A:\n", A)
print("Matrix B:\n", B)
trA=np.trace(A)
trB=np.trace(B)
print("Trace of Matrix A:", trA)
print("Trace of Matrix B:", trB)



5.10의 연습문제를 풀어본다.

# 아래의 벡터를 정의하고, 기본적인 산술 연산을 해보자.
# 연산이 성립하지 않는 경우  그 이유를 생각해보자.