#### 행렬과 벡터의 곱(연산)의 결과는 벡터이다.

In [29]:
import numpy as np

A= np.array([[4,3,0],[1,1, 9],[0,3,0], [1,1,1]])
#print(A)
b= np.array([[0],[7],[1]])
#print(b)
c=A@b
#print(c)

D= np.array([[4,0,2,0,8,0],[0,3,0,5,0,1]])
#print(D)
e= np.array([[4],[6],[1],[2],[1],[6]])
#print(e)
f=D@e
print(f)



[[26]
 [34]]


#### 행렬을 대칭행렬로 만들어 보고 C=1/2(A+A^T)

In [30]:
G=np.array([[1,11,1],[-5,-2,1],[-1,-5,2]])
#print(G)
H=1/2*(G+G.T)
print(H)

I=np.array([[-3,0,-2,-2],[-1,-3,-2,-6],[-4,-8,-7,4],[6,-2,5,4]])
print(I)
J=1/2*(I+I.T)       
print(J)

[[ 1.  3.  0.]
 [ 3. -2. -2.]
 [ 0. -2.  2.]]
[[-3  0 -2 -2]
 [-1 -3 -2 -6]
 [-4 -8 -7  4]
 [ 6 -2  5  4]]
[[-3.  -0.5 -3.   2. ]
 [-0.5 -3.  -5.  -4. ]
 [-3.  -5.  -7.   4.5]
 [ 2.  -4.   4.5  4. ]]


##### 행렬에 자신의 전치 행렬을 곱해서 대칭행렬 만들기

In [31]:
K=np.array([[3,0,3],[0,7,0]])
L=K@K.T
print(L)
M=K.T@K
print(M)


[[18  0]
 [ 0 49]]
[[ 9  0  9]
 [ 0 49  0]
 [ 9  0  9]]


In [32]:
N=np.array([[1,6],[6,1]])
O=N.T@N
print(O)
P=N@N.T
print(P)


[[37 12]
 [12 37]]
[[37 12]
 [12 37]]


##### Hadamard - multiply using  *


In [ ]:
M1=np.random.randint(1,10,(4,3))
M2=np.random.randint(1,10,(4,3))
print(M1)
print(M2)

M3=M1*M2
print(M3)

M3=np.array([[-4,-3,-9],[-5,-2,3],[0,-7,7]])
M4=np.array([[-1,4,-3],[-3,-4,2],[3,2,5]])
print(M3)
print(M4)
print(M3*M4)


###### vectorization of a matrix

In [ ]:
P1=np.array([[1,2,3],[4,5,6]])
print(P1.flatten(order='F'))  # Fortran-style column-major order
print(P1.flatten(order='C'))  # C-style row-major order


##### Frobenious inner product

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
f=np.trace(A.T@B)
print(f)

A1=np.array([[4,2],[3,2],[-5,-1]])
A2=np.array([[7,-2],[-7,-8],[-1,8]])
f1=np.trace(A1.T@A2)
print(f1)

B1=np.array([[6,1,2],[3,3,-2]])
B2=np.array([[4,-11,1],[6,1,-2]])

f2=np.trace(B1.T@B2)
print(f2)




