In [ ]:
import numpy as np
import math

A=np.random.randint(1,10,(4,3))
print(A)
print("Frobenius norm of the matrix is", np.linalg.norm(A,'fro'))  # Frobenius norm
print("L1 norm of the matrix is", np.linalg.norm(A,1))  # L1 norm
print("L2 norm of the matrix is", np.linalg.norm(A,2))  # L2 norm
print("Nuclear norm of the matrix is", np.linalg.norm(A,'nuc')) # Nuclear norm

print("Infinity norm of the matrix is", np.linalg.norm(A, np.inf))  # Infinity norm
print("Negative infinity norm of the matrix is", np.linalg.norm(A, -np.inf))  # Negative infinity norm
print("L1 norm of the matrix is", np.linalg.norm(A, ord=1))  # L1 norm (alternative syntax)
print("L2 norm of the matrix is", np.linalg.norm(A, ord=2))  # L2 norm (alternative syntax)


[[4 5 8]
 [8 7 1]
 [9 7 5]
 [3 1 7]]
Frobenius norm of the matrix is 20.808652046684813
L1 norm of the matrix is 24.0
L2 norm of the matrix is 19.307748155310094
Nuclear norm of the matrix is 28.633647278238545
Infinity norm of the matrix is 21.0
Negative infinity norm of the matrix is 11.0
L1 norm of the matrix is 24.0
L2 norm of the matrix is 19.307748155310094


##### Forbenius Matrix Norm

In [8]:
# Create another matrix B of the same shape as A
B = np.random.randint(1, 10, (4, 3))
print("Matrix B:")
print(B)

# Compute Euclidean distance between A and B
euclidean_distance = np.linalg.norm(A - B, 'fro')
print("\nEuclidean distance between matrices A and B:", euclidean_distance)

Matrix B:
[[2 9 7]
 [6 6 8]
 [5 2 1]
 [4 3 5]]

Euclidean distance between matrices A and B: 11.874342087037917


In [12]:
E1=np.array([[4,2],[3, 2], [-5, -1]])
E2=np.array([[7,-2],[-7, -8], [-1, 8]])

euclidean_distance_E1_E2 = np.linalg.norm(E1 - E2, 'fro')

result=math.sqrt(322)
print(result)
dist1=np.linalg.matrix_norm(E1-E2, ord='fro')
print("Euclidean distance between E1 and E2:", dist1)
print(E1-E2)
print("\nEuclidean distance between matrices E1 and E2:", euclidean_distance_E1_E2)


17.944358444926362
Euclidean distance between E1 and E2: 17.944358444926362
[[-3  4]
 [10 10]
 [-4 -9]]

Euclidean distance between matrices E1 and E2: 17.944358444926362


In [ ]:
F1=np.array([[6,1, 2], [3,3,-2]])
F2=np.array([[4, -11, 1], [6, 1, -2]])
print("F1-F2 : ")
print((F1-F2))
euclidean_distance_F1_F2 = np.linalg.norm(F1 - F2, 'fro')
print("Euclidean distance between F1 and F2:", euclidean_distance_F1_F2)