In [5]:
import numpy as np
import math

TMP=np.array([[-0.5,0.5],[0.5,0.5]])
TMP

array([[-0.5,  0.5],
       [ 0.5,  0.5]])

In [6]:
TMP_T=TMP.T
TMP_T

array([[-0.5,  0.5],
       [ 0.5,  0.5]])

In [7]:
AA=TMP@TMP_T
AA

array([[0.5, 0. ],
       [0. , 0.5]])

In [11]:
KA=-1*math.sqrt(2)*TMP
KA

array([[ 0.70710678, -0.70710678],
       [-0.70710678, -0.70710678]])

In [12]:
KA_T=KA.T
KA

array([[ 0.70710678, -0.70710678],
       [-0.70710678, -0.70710678]])

In [18]:
TMP_KK=KA@KA_T
TMP_KK

array([[ 1.00000000e+00, -4.26642159e-17],
       [-4.26642159e-17,  1.00000000e+00]])

In [ ]:
import sympy as sp

# 미지수 zeta 정의
zeta = sp.Symbol('zeta')

# 행렬 정의 (미지수 포함)
M = sp.Matrix([[0,2**(-0.5), 2**(-0.5)],
               [0,2**(-0.5), -2**(-0.5)],
               [zeta,0,0]])
M


Matrix([
[   0, 0.707106781186548,  0.707106781186548],
[   0, 0.707106781186548, -0.707106781186548],
[zeta,                 0,                  0]])

In [23]:
# 전치 행렬과 곱
ATA = M.T * M

ATA

Matrix([
[zeta**2,   0,   0],
[      0, 1.0,   0],
[      0,   0, 1.0]])

In [35]:
print("A^T A =")
sp.pprint(ATA)

# 직교 조건: A^T A = I
eq = sp.Eq(ATA, sp.eye(2))

# 방정식 풀기
solution = sp.solve(eq, zeta)
print("alpha solutions:", solution)


A^T A =
⎡ 2          ⎤
⎢ζ    0    0 ⎥
⎢            ⎥
⎢0   1.0   0 ⎥
⎢            ⎥
⎣0    0   1.0⎦
alpha solutions: []


In [30]:
Q1 = sp.Matrix([[0,2**(-0.5), 2**(-0.5)],
               [0,2**(-0.5), -2**(-0.5)],
               [-1,0,0]])
QQ=Q1.T*Q1
print(QQ)
QQQ=Q1*Q1.T
print(QQQ)



Matrix([[1, 0, 0], [0, 1.00000000000000, 0], [0, 0, 1.00000000000000]])
Matrix([[1.00000000000000, 0, 0], [0, 1.00000000000000, 0], [0, 0, 1]])


In [31]:
C=sp.Matrix([[sp.cos(zeta),-sp.sin(zeta),0],
             [sp.sin(zeta),sp.cos(zeta),0],
             [0,0,1]])
C

Matrix([
[cos(zeta), -sin(zeta), 0],
[sin(zeta),  cos(zeta), 0],
[        0,          0, 1]])

In [32]:
TMP1=C*C.T
TMP1

Matrix([
[sin(zeta)**2 + cos(zeta)**2,                           0, 0],
[                          0, sin(zeta)**2 + cos(zeta)**2, 0],
[                          0,                           0, 1]])

In [33]:
TMP2=C.T*C
TMP2

Matrix([
[sin(zeta)**2 + cos(zeta)**2,                           0, 0],
[                          0, sin(zeta)**2 + cos(zeta)**2, 0],
[                          0,                           0, 1]])

In [36]:
import sympy as sp

# 1. 벡터 집합 정의
v1 = sp.Matrix([1, 1, 0])
v2 = sp.Matrix([1, 0, 1])
v3 = sp.Matrix([0, 1, 1])

vectors = [v1, v2, v3]

# 2. Gram-Schmidt 과정 직접 구현
orthogonal_vectors = []
orthonormal_vectors = []

for i, v in enumerate(vectors):
    # (a) 이전 벡터들의 성분 제거
    u = v
    for q in orthogonal_vectors:
        proj = (v.dot(q) / q.dot(q)) * q
        u = u - proj
    
    orthogonal_vectors.append(u)
    
    # (b) 정규화 (길이를 1로 맞춤)
    q_normalized = u / sp.sqrt(u.dot(u))
    orthonormal_vectors.append(q_normalized)

# 3. 결과 출력
print("원래 벡터 집합:")
for v in vectors:
    print(v)

print("\n직교 벡터 집합 (orthogonal):")
for u in orthogonal_vectors:
    print(u)

print("\n직교 정규 벡터 집합 (orthonormal):")
for q in orthonormal_vectors:
    print(q)


원래 벡터 집합:
Matrix([[1], [1], [0]])
Matrix([[1], [0], [1]])
Matrix([[0], [1], [1]])

직교 벡터 집합 (orthogonal):
Matrix([[1], [1], [0]])
Matrix([[1/2], [-1/2], [1]])
Matrix([[-2/3], [2/3], [2/3]])

직교 정규 벡터 집합 (orthonormal):
Matrix([[sqrt(2)/2], [sqrt(2)/2], [0]])
Matrix([[sqrt(6)/6], [-sqrt(6)/6], [sqrt(6)/3]])
Matrix([[-sqrt(3)/3], [sqrt(3)/3], [sqrt(3)/3]])


In [ ]:
import sympy as sp

# 1. 벡터 집합 정의
v1 = sp.Matrix([1, 3])
v2 = sp.Matrix([1, -1])
v3 = sp.Matrix([-2,1])

vectors = [v1, v2, v3]

# 2. Gram-Schmidt 과정 직접 구현
orthogonal_vectors = []
orthonormal_vectors = []

for i, v in enumerate(vectors):
    # (a) 이전 벡터들의 성분 제거
    u = v
    for q in orthogonal_vectors:
        proj = (v.dot(q) / q.dot(q)) * q
        u = u - proj
    
    orthogonal_vectors.append(u)
    
    # (b) 정규화 (길이를 1로 맞춤)
    q_normalized = u / sp.sqrt(u.dot(u))
    orthonormal_vectors.append(q_normalized)

# 3. 결과 출력
print("원래 벡터 집합:")
for v in vectors:
    print(v)

print("\n직교 벡터 집합 (orthogonal):")
for u in orthogonal_vectors:
    print(u)

print("\n직교 정규 벡터 집합 (orthonormal):")
for q in orthonormal_vectors:
    print(q)


원래 벡터 집합:
Matrix([[1], [3]])
Matrix([[1], [-1]])
Matrix([[-2], [1]])

직교 벡터 집합 (orthogonal):
Matrix([[1], [3]])
Matrix([[6/5], [-2/5]])
Matrix([[0], [0]])

직교 정규 벡터 집합 (orthonormal):
Matrix([[sqrt(10)/10], [3*sqrt(10)/10]])
Matrix([[3*sqrt(10)/10], [-sqrt(10)/10]])
Matrix([[0], [0]])


In [38]:
v

Matrix([
[-2],
[ 1]])

In [39]:
u

Matrix([
[0],
[0]])

In [40]:
q


Matrix([
[0],
[0]])

In [1]:
import sympy as sp

# 1. 벡터 집합 정의
v1 = sp.Matrix([1, 1])
v2 = sp.Matrix([3, 4])


vectors = [v1, v2]

# 2. Gram-Schmidt 과정 직접 구현
orthogonal_vectors = []
orthonormal_vectors = []

for i, v in enumerate(vectors):
    # (a) 이전 벡터들의 성분 제거
    u = v
    for q in orthogonal_vectors:
        proj = (v.dot(q) / q.dot(q)) * q
        u = u - proj
    
    orthogonal_vectors.append(u)
    
    # (b) 정규화 (길이를 1로 맞춤)
    q_normalized = u / sp.sqrt(u.dot(u))
    orthonormal_vectors.append(q_normalized)

# 3. 결과 출력
print("원래 벡터 집합:")
for v in vectors:
    print(v)

print("\n직교 벡터 집합 (orthogonal):")
for u in orthogonal_vectors:
    print(u)

print("\n직교 정규 벡터 집합 (orthonormal):")
for q in orthonormal_vectors:
    print(q)


원래 벡터 집합:
Matrix([[1], [1]])
Matrix([[3], [4]])

직교 벡터 집합 (orthogonal):
Matrix([[1], [1]])
Matrix([[-1/2], [1/2]])

직교 정규 벡터 집합 (orthonormal):
Matrix([[sqrt(2)/2], [sqrt(2)/2]])
Matrix([[-sqrt(2)/2], [sqrt(2)/2]])


In [2]:
import sympy as sp

# 1. 벡터 집합 정의
v1 = sp.Matrix([1, 3])
v2 = sp.Matrix([-3, 4])


vectors = [v1, v2]

# 2. Gram-Schmidt 과정 직접 구현
orthogonal_vectors = []
orthonormal_vectors = []

for i, v in enumerate(vectors):
    # (a) 이전 벡터들의 성분 제거
    u = v
    for q in orthogonal_vectors:
        proj = (v.dot(q) / q.dot(q)) * q
        u = u - proj
    
    orthogonal_vectors.append(u)
    
    # (b) 정규화 (길이를 1로 맞춤)
    q_normalized = u / sp.sqrt(u.dot(u))
    orthonormal_vectors.append(q_normalized)

# 3. 결과 출력
print("원래 벡터 집합:")
for v in vectors:
    print(v)

print("\n직교 벡터 집합 (orthogonal):")
for u in orthogonal_vectors:
    print(u)

print("\n직교 정규 벡터 집합 (orthonormal):")
for q in orthonormal_vectors:
    print(q)


원래 벡터 집합:
Matrix([[1], [3]])
Matrix([[-3], [4]])

직교 벡터 집합 (orthogonal):
Matrix([[1], [3]])
Matrix([[-39/10], [13/10]])

직교 정규 벡터 집합 (orthonormal):
Matrix([[sqrt(10)/10], [3*sqrt(10)/10]])
Matrix([[-3*sqrt(10)/10], [sqrt(10)/10]])


In [3]:
import sympy as sp

def gram_schmidt(A):
    """
    Perform Gram-Schmidt orthogonalization on the columns of matrix A.
    Returns an orthonormal matrix Q (with Sympy exact arithmetic).
    """
    # Convert to sympy Matrix
    A = sp.Matrix(A)
    n = A.shape[1]
    Q = []
    
    for j in range(n):
        v = A[:, j]
        for i in range(j):
            proj = (Q[i].dot(v)) * Q[i]
            v = v - proj
        v = v / sp.sqrt(v.dot(v))  # normalize
        Q.append(v)
    
    return sp.Matrix.hstack(*Q)

# Define the matrix
A = sp.Matrix([[1, 3],
               [-3, 4]])

# Apply Gram-Schmidt
Q = gram_schmidt(A)

print("Original matrix A:")
sp.pprint(A)
print("\nOrthogonal (Orthonormal) matrix Q:")
sp.pprint(Q)

# Verify orthogonality: Q^T * Q should be identity
print("\nQ^T Q:")
sp.pprint(Q.T * Q)


Original matrix A:
⎡1   3⎤
⎢     ⎥
⎣-3  4⎦

Orthogonal (Orthonormal) matrix Q:
⎡  √10    3⋅√10⎤
⎢  ───    ─────⎥
⎢  10      10  ⎥
⎢              ⎥
⎢-3⋅√10    √10 ⎥
⎢───────   ─── ⎥
⎣  10      10  ⎦

Q^T Q:
⎡1  0⎤
⎢    ⎥
⎣0  1⎦
