In [3]:
import numpy as np

def calculate_matrix_properties(matrix):
    """
    Calculate properties of a matrix, including mean, variance, standard deviation, max, min, sum along rows and columns.

    Args:
    matrix (list of lists): A 2D list representing the matrix.

    Returns:
    dict: A dictionary containing the calculated properties.  Returns None if the matrix is not valid (not 2x2 or not a list).
    """
    if not isinstance(matrix, list) or len(matrix) != 3 or not all(isinstance(row, list) and len(row) == 3 for row in matrix):
        raise ValueError("List must contain three lists, each with three values.")

    np_matrix = np.array(matrix)

    calculations = {
        'mean': [np.mean(np_matrix, axis=0).tolist(), np.mean(np_matrix, axis=1).tolist(), np.mean(np_matrix)],
        'variance': [np.var(np_matrix, axis=0).tolist(), np.var(np_matrix, axis=1).tolist(), np.var(np_matrix)],
        'standard deviation': [np.std(np_matrix, axis=0).tolist(), np.std(np_matrix, axis=1).tolist(), np.std(np_matrix)],
        'max': [np.max(np_matrix, axis=0).tolist(), np.max(np_matrix, axis=1).tolist(), np.max(np_matrix)],
        'min': [np.min(np_matrix, axis=0).tolist(), np.min(np_matrix, axis=1).tolist(), np.min(np_matrix)],
        'sum': [np.sum(np_matrix, axis=0).tolist(), np.sum(np_matrix, axis=1).tolist(), np.sum(np_matrix)]
    }

    return calculations

In [4]:
def calculate_minors(matrix):
    """
    Calculate the matrix of minors for a 3x3 matrix.
    Each element in the matrix of minors is the determinant of the 2x2 matrix 
    formed by removing the row and column of the current element.
    
    Args:
    matrix (list of lists): A 3x3 matrix
    
    Returns:
    numpy.ndarray: The matrix of minors
    """
    np_matrix = np.array(matrix)
    minors = np.zeros((3, 3))
    
    for i in range(3):
        for j in range(3):
            # Delete i-th row and j-th column
            minor = np.delete(np.delete(np_matrix, i, axis=0), j, axis=1)
            # Calculate determinant of the resulting 2x2 matrix
            minors[i,j] = np.linalg.det(minor)
            
    return minors

In [6]:
Sample_matrix = np.array([
    [1, 2, 3],[4,5,6],[7,8,9]])

In [7]:
print(calculate_minors(Sample_matrix))

[[ -3.  -6.  -3.]
 [ -6. -12.  -6.]
 [ -3.  -6.  -3.]]


In [8]:
matrix1 = np.array([
    [ 3,4,1],[0,2,3],[5,4,1]])
m1= calculate_minors(matrix1);m1

array([[-10., -15., -10.],
       [  0.,  -2.,  -8.],
       [ 10.,   9.,   6.]])

In [9]:
def calculate_cofactors(matrix):
    """
    Calculate the cofactor matrix for a 3x3 matrix.
    The cofactor matrix is obtained by multiplying each element in the matrix of minors
    by (-1)^(i+j).
    
    Args:
    matrix (list of lists or numpy.ndarray): A 3x3 matrix
    
    Returns:
    numpy.ndarray: The cofactor matrix
    """
    minors = calculate_minors(matrix)
    cofactors = np.zeros((3, 3))
    
    for i in range(3):
        for j in range(3):
            cofactors[i,j] = minors[i,j] * (-1)**(i+j)
            
    return cofactors

In [10]:
c1= calculate_cofactors(Sample_matrix);c1

array([[ -3.,   6.,  -3.],
       [  6., -12.,   6.],
       [ -3.,   6.,  -3.]])

In [11]:
c2 = calculate_cofactors(matrix1);c2

array([[-10.,  15., -10.],
       [ -0.,  -2.,   8.],
       [ 10.,  -9.,   6.]])