In [1]:
import numpy as np

def calculate_matrix_properties(matrix):
    """
    Calculate properties of a matrix, including mean, variance, standard deviation, max, min, sum along rows and columns.

    Args:
    matrix (list of lists): A 2D list representing the matrix.

    Returns:
    dict: A dictionary containing the calculated properties.  Returns None if the matrix is not valid (not 2x2 or not a list).
    """
    if not isinstance(matrix, list) or len(matrix) != 3 or not all(isinstance(row, list) and len(row) == 3 for row in matrix):
        raise ValueError("List must contain three lists, each with three values.")

    np_matrix = np.array(matrix)

    calculations = {
        'mean': [np.mean(np_matrix, axis=0).tolist(), np.mean(np_matrix, axis=1).tolist(), np.mean(np_matrix)],
        'variance': [np.var(np_matrix, axis=0).tolist(), np.var(np_matrix, axis=1).tolist(), np.var(np_matrix)],
        'standard deviation': [np.std(np_matrix, axis=0).tolist(), np.std(np_matrix, axis=1).tolist(), np.std(np_matrix)],
        'max': [np.max(np_matrix, axis=0).tolist(), np.max(np_matrix, axis=1).tolist(), np.max(np_matrix)],
        'min': [np.min(np_matrix, axis=0).tolist(), np.min(np_matrix, axis=1).tolist(), np.min(np_matrix)],
        'sum': [np.sum(np_matrix, axis=0).tolist(), np.sum(np_matrix, axis=1).tolist(), np.sum(np_matrix)]
    }

    return calculations

In [4]:
def calculate_minors(matrix):
    """
    Calculate the matrix of minors for a 3x3 matrix.
    Each element in the matrix of minors is the determinant of the 2x2 matrix 
    formed by removing the row and column of the current element.
    
    Args:
    matrix (list of lists): A 3x3 matrix
    
    Returns:
    numpy.ndarray: The matrix of minors
    """
    np_matrix = np.array(matrix)
    minors = np.zeros((3, 3))
    
    for i in range(3):
        for j in range(3):
            # Delete i-th row and j-th column
            minor = np.delete(np.delete(np_matrix, i, axis=0), j, axis=1)
            # Calculate determinant of the resulting 2x2 matrix
            minors[i,j] = np.linalg.det(minor)
            
    return minors

In [3]:
Sample_matrix = np.array([
    [1, 2, 3],[4,5,6],[7,8,9]])

In [5]:
print(calculate_minors(Sample_matrix))

[[ -3.  -6.  -3.]
 [ -6. -12.  -6.]
 [ -3.  -6.  -3.]]


In [6]:
matrix1 = np.array([
    [ 3,4,1],[0,2,3],[5,4,1]])
m1= calculate_minors(matrix1);m1

array([[-10., -15., -10.],
       [  0.,  -2.,  -8.],
       [ 10.,   9.,   6.]])

In [7]:
def calculate_cofactors(matrix):
    """
    Calculate the cofactor matrix for a 3x3 matrix.
    The cofactor matrix is obtained by multiplying each element in the matrix of minors
    by (-1)^(i+j).
    
    Args:
    matrix (list of lists or numpy.ndarray): A 3x3 matrix
    
    Returns:
    numpy.ndarray: The cofactor matrix
    """
    minors = calculate_minors(matrix)
    cofactors = np.zeros((3, 3))
    
    for i in range(3):
        for j in range(3):
            cofactors[i,j] = minors[i,j] * (-1)**(i+j)
            
    return cofactors

In [8]:
c1= calculate_cofactors(Sample_matrix);c1

array([[ -3.,   6.,  -3.],
       [  6., -12.,   6.],
       [ -3.,   6.,  -3.]])

In [9]:
c2 = calculate_cofactors(matrix1);c2

array([[-10.,  15., -10.],
       [ -0.,  -2.,   8.],
       [ 10.,  -9.,   6.]])

In [10]:
from scipy import linalg
import sympy as sp

def calculate_determinants(matrix):
    """
    Calculate determinant using different methods (NumPy, SciPy, and SymPy)
    
    Args:
    matrix: Input matrix (numpy array)
    
    Returns:
    dict: Determinants calculated using different methods
    """
    # NumPy determinant
    np_det = np.linalg.det(matrix)
    
    # SciPy determinant
    scipy_det = linalg.det(matrix)
    
    # SymPy determinant
    sympy_matrix = sp.Matrix(matrix)
    sympy_det = float(sympy_matrix.det())
    
    return {
        'numpy_det': np_det,
        'scipy_det': scipy_det,
        'sympy_det': sympy_det
    }

# Test with both matrices
print("Sample_matrix determinants:")
print(calculate_determinants(Sample_matrix))
print("\nmatrix1 determinants:")
print(calculate_determinants(matrix1))

Sample_matrix determinants:
{'numpy_det': np.float64(0.0), 'scipy_det': np.float64(0.0), 'sympy_det': 0.0}

matrix1 determinants:
{'numpy_det': np.float64(19.99999999999999), 'scipy_det': np.float64(20.0), 'sympy_det': 20.0}


In [11]:
m2=m1.T;m2


array([[-10.,   0.,  10.],
       [-15.,  -2.,   9.],
       [-10.,  -8.,   6.]])

In [13]:
def calculate_inverse(matrix):
    """
    Calculate the inverse of a 3x3 matrix using NumPy.
    
    Args:
    matrix (numpy.ndarray): A 3x3 matrix
    
    Returns:
    numpy.ndarray: The inverse of the matrix.  Returns None if the matrix is singular.
    """
    try:
        inverse = np.linalg.inv(matrix)
        return inverse
    except np.linalg.LinAlgError:
        return None  # Matrix is singular (non-invertible)

# Test with both matrices
print("Inverse of Sample_matrix:")
print(calculate_inverse(Sample_matrix))
print("\nInverse of matrix1:")
print(calculate_inverse(matrix1))

Inverse of Sample_matrix:
None

Inverse of matrix1:
[[-5.00000000e-01  6.66133815e-17  5.00000000e-01]
 [ 7.50000000e-01 -1.00000000e-01 -4.50000000e-01]
 [-5.00000000e-01  4.00000000e-01  3.00000000e-01]]


KeyError: 0

In [26]:
AA=np.array([[1,1],[1,4]])
det_A= np.linalg.det(AA);det_A
print("Determinant of AA:", det_A)
inv_AA = np.linalg.inv(AA)
print("Inverse of AA:", inv_AA)



Determinant of AA: 3.0000000000000004
Inverse of AA: [[ 1.33333333 -0.33333333]
 [-0.33333333  0.33333333]]


In [32]:
BB=np.array([[2,2,4],[4,2,5],[1,2,1]])
minors_BB = calculate_minors(BB)
print("Minors of BB:")
print(minors_BB)
cofactors_BB = calculate_cofactors(BB)
print("Cofactors of BB:")
print(cofactors_BB)
det__BB = np.linalg.det(BB)
print("Determinant of BB:", det__BB)
adjugated_BB = cofactors_BB.T
print("Adjugated BB:")
print(adjugated_BB)
print("Inverse of BB:")
print(np.linalg.inv(BB))
print(det__BB , adjugated_BB)


Minors of BB:
[[-8. -1.  6.]
 [-6. -2.  2.]
 [ 2. -6. -4.]]
Cofactors of BB:
[[-8.  1.  6.]
 [ 6. -2. -2.]
 [ 2.  6. -4.]]
Determinant of BB: 9.999999999999998
Adjugated BB:
[[-8.  6.  2.]
 [ 1. -2.  6.]
 [ 6. -2. -4.]]
Inverse of BB:
[[-0.8  0.6  0.2]
 [ 0.1 -0.2  0.6]
 [ 0.6 -0.2 -0.4]]
9.999999999999998 [[-8.  6.  2.]
 [ 1. -2.  6.]
 [ 6. -2. -4.]]


In [35]:
CC=np.array([[1,-5,4],[-1,-15,6],[2,0,3]])
minors_CC = calculate_minors(CC)
print("Minors of CC:")
print(minors_CC)
cofactors_CC = calculate_cofactors(CC)
print("Cofactors of CC:")
print(cofactors_CC)
det__CC = np.linalg.det(CC)
print("Determinant of CC:", det__CC)
adjugated_CC = cofactors_CC.T
print("Adjugated CC:")
print(adjugated_CC)
print("Inverse of CC:")
if det__CC != 0:
    print(np.linalg.inv(CC))
else:
    print("Matrix is singular, cannot compute inverse.")


Minors of CC:
[[-45. -15.  30.]
 [-15.  -5.  10.]
 [ 30.  10. -20.]]
Cofactors of CC:
[[-45.  15.  30.]
 [ 15.  -5. -10.]
 [ 30. -10. -20.]]
Determinant of CC: 0.0
Adjugated CC:
[[-45.  15.  30.]
 [ 15.  -5. -10.]
 [ 30. -10. -20.]]
Inverse of CC:
Matrix is singular, cannot compute inverse.


In [36]:
import numpy as np

AAA=np.random.randn(3, 3)
AAA_i=np.linalg.inv(AAA)
print("Random 3x3 Matrix AAA:")
print(AAA)
print("Inverse of AAA:")
print(AAA_i)



Random 3x3 Matrix AAA:
[[ 0.04106519 -0.73376966 -0.98488815]
 [-0.49374025  2.16500388 -0.2472837 ]
 [-0.58022931  0.8931191  -2.45808674]]
Inverse of AAA:
[[ 22.45929075  11.81451763 -10.18736501]
 [  4.71197436   2.96058525  -2.18579437]
 [ -3.58945204  -1.71311049   1.20371386]]
