In [ ]:
import numpy as np

def augment_and_rref(matrix):
    # Convert input to numpy array if it isn't already
    matrix = np.array(matrix, dtype=float)
    rows, cols = matrix.shape
    
    # Create identity matrix of same height
    identity = np.eye(rows)
    
    # Augment the original matrix with identity matrix
    augmented = np.hstack((matrix, identity))
    
    # print("Augmented Matrix:")
    # print(augmented)    
    
    # Gaussian elimination with full pivoting
    for i in range(rows):
        # Find pivot
        pivot = augmented[i][i]
        if pivot == 0:
            # Find non-zero pivot
            for j in range(i + 1, rows):
                if augmented[j][i] != 0:
                    # Swap rows
                    augmented[i], augmented[j] = augmented[j].copy(), augmented[i].copy()
                    pivot = augmented[i][i]
                    break
                    
        # Make pivot 1
        augmented[i] = augmented[i] / pivot
        
        # Make other elements in column 0
        for j in range(rows):
            if i != j:
                augmented[j] = augmented[j] - augmented[i] * augmented[j][i]
    
    inverse_matrix = augmented[:, cols:]  # Extract the inverse matrix from the augmented matrix
    return inverse_matrix.round(10)  # Return the reduced row echelon form



In [46]:
# Example usage:
A = np.array([[1, 2], [3, 4]])
result = augment_and_rref(A)
print("Reduced Row Echelon Form:")
print(result)


Reduced Row Echelon Form:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [44]:
print("Reduced Row Echelon Form:")
print(result)

Reduced Row Echelon Form:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [47]:

bb=np.array([[3,4,1], [0,2,3], [5,4,1]])
result = augment_and_rref(bb)
print("Reduced Row Echelon Form:")  
print(result)


Reduced Row Echelon Form:
[[-0.5   0.    0.5 ]
 [ 0.75 -0.1  -0.45]
 [-0.5   0.4   0.3 ]]


In [49]:
rr=np.array([[1,1],[1,4]])
result = augment_and_rref(rr)
print("Reduced Row Echelon Form:")  
print(result)

Reduced Row Echelon Form:
[[ 1.33333333 -0.33333333]
 [-0.33333333  0.33333333]]


In [50]:
cc=np.array([[2,2,4], [4,2,5], [1,2,1]])
result = augment_and_rref(cc)
print("Reduced Row Echelon Form:")  
print(result)


Reduced Row Echelon Form:
[[-0.8  0.6  0.2]
 [ 0.1 -0.2  0.6]
 [ 0.6 -0.2 -0.4]]
