In [ ]:
import numpy as np
import sympy as sym

A=np.random.randn(3,3   )
print(A)
Acat=np.concatenate((A, np.eye(3,3)), axis=1)
#print(Acat)
Ar=sym.Matrix(Acat).rref()[0]
#print(Ar)
Ar=Ar[:, 3:]  # Extract the original matrix part
print("Rref-method:")
print(Ar)
print("Inverse of A:")
Ai=np.linalg.inv(A)
print(Ai)

print("Difference between RREF and Inverse:")
print(Ar-Ai)



[[-1.24435103 -0.43459854 -0.75157706]
 [-1.78004699 -1.29851304 -0.92647731]
 [ 1.04491858 -0.83572365  0.35647838]]
Rref-method:
Matrix([[2.72862960077050, -1.72701647447651, 1.26440719155031], [0.735647026410357, -0.753748992947466, -0.407979626645984], [-6.27358714516836, 3.29519496020419, -1.85750619198389]])
Inverse of A:
[[ 2.7286296  -1.72701647  1.26440719]
 [ 0.73564703 -0.75374899 -0.40797963]
 [-6.27358715  3.29519496 -1.85750619]]
Difference between RREF and Inverse:
Matrix([[0, -4.44089209850063e-16, 0], [2.22044604925031e-16, -1.11022302462516e-16, -5.55111512312578e-17], [-2.66453525910038e-15, 8.88178419700125e-16, -2.22044604925031e-16]])
