In [1]:
import numpy as np

def augment_and_rref(matrix):
    # Convert input to numpy array if it isn't already
    matrix = np.array(matrix, dtype=float)
    rows, cols = matrix.shape
    
    # Create identity matrix of same height
    identity = np.eye(rows)
    
    # Augment the original matrix with identity matrix
    augmented = np.hstack((matrix, identity))
    
    # print("Augmented Matrix:")
    # print(augmented)    
    
    # Gaussian elimination with full pivoting
    for i in range(rows):
        # Find pivot
        pivot = augmented[i][i]
        if pivot == 0:
            # Find non-zero pivot
            for j in range(i + 1, rows):
                if augmented[j][i] != 0:
                    # Swap rows
                    augmented[i], augmented[j] = augmented[j].copy(), augmented[i].copy()
                    pivot = augmented[i][i]
                    break
                    
        # Make pivot 1
        augmented[i] = augmented[i] / pivot
        
        # Make other elements in column 0
        for j in range(rows):
            if i != j:
                augmented[j] = augmented[j] - augmented[i] * augmented[j][i]
    
    inverse_matrix = augmented[:, cols:]  # Extract the inverse matrix from the augmented matrix
    return inverse_matrix.round(10)  # Return the reduced row echelon form



In [5]:
# Example usage:
A = np.array([[1, 2], [3, 4]])
result = augment_and_rref(A)
print("Inverse Matrix:")
print(result)


Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
bb=np.array([[3,4,1], [0,2,3], [5,4,1]])
result = augment_and_rref(bb)
print("Inverse Matrix:")  
print(result)


Inverse Matrix:
[[-0.5   0.    0.5 ]
 [ 0.75 -0.1  -0.45]
 [-0.5   0.4   0.3 ]]


In [8]:
rr=np.array([[1,1],[1,4]])
result = augment_and_rref(rr)
print("Inverse Matrix:")  
print(result)

Inverse Matrix:
[[ 1.33333333 -0.33333333]
 [-0.33333333  0.33333333]]


In [10]:
cc=np.array([[2,2,4], [4,2,5], [1,2,1]])
result = augment_and_rref(cc)
print("inverse Matrix:")  
print(result)


inverse Matrix:
[[-0.8  0.6  0.2]
 [ 0.1 -0.2  0.6]
 [ 0.6 -0.2 -0.4]]


In [11]:
aa=np.array([[-4,7],[3,-8]])
result = augment_and_rref(aa)
print("Inverse Matrix:")
print(result)

Inverse Matrix:
[[-0.72727273 -0.63636364]
 [-0.27272727 -0.36363636]]


In [14]:
bb=np.array([[1,0,2], [1,2,1], [1,0,2]])
det_bb = np.linalg.det(bb)

print("Determinant of bb:", det_bb)


result = augment_and_rref(bb)
print("Inverse Matrix:")
print(result)

Determinant of bb: 0.0
Inverse Matrix:
[[ inf  nan -inf]
 [-inf  nan  inf]
 [-inf  nan  inf]]


C:\Users\chaos\AppData\Local\Temp\ipykernel_1196\1067809523.py:31: RuntimeWarning: divide by zero encountered in divide
  augmented[i] = augmented[i] / pivot
C:\Users\chaos\AppData\Local\Temp\ipykernel_1196\1067809523.py:31: RuntimeWarning: invalid value encountered in divide
  augmented[i] = augmented[i] / pivot


In [15]:
cc=np.array([[1,0,2,5],[3,0,0,1],[0,4,5,0],[5,8,2,-17]])
result = augment_and_rref(cc)
det_cc = np.linalg.det(cc)
print("Determinant of cc:", det_cc)
print("Inverse Matrix:")
print(result)


Determinant of cc: 0.0
Inverse Matrix:
[[-inf  inf  inf -inf]
 [ inf -inf -inf  inf]
 [-inf  inf  inf -inf]
 [ inf -inf -inf  inf]]


C:\Users\chaos\AppData\Local\Temp\ipykernel_1196\1067809523.py:31: RuntimeWarning: divide by zero encountered in divide
  augmented[i] = augmented[i] / pivot
C:\Users\chaos\AppData\Local\Temp\ipykernel_1196\1067809523.py:31: RuntimeWarning: invalid value encountered in divide
  augmented[i] = augmented[i] / pivot


In [16]:
dd=np.array([[1,0,2,5],[3,0,0,1],[0,4,5,0],[0,3,4,0]])
result = augment_and_rref(dd)
print("Inverse Matrix:")
print(result)

Inverse Matrix:
[[-0.07142857  0.35714286 -0.42857143  0.57142857]
 [ 0.         -0.          4.         -5.        ]
 [ 0.          0.         -3.          4.        ]
 [ 0.21428571 -0.07142857  1.28571429 -1.71428571]]
