### linspace() 문법
numpy.linspace()는 선형적으로 일정한 간격을 가진 수열을 생성하는 함수입니다.
주로 데이터 생성이나 그래프 그리기에서 많이 사용됩니다.

###### 기본 문법
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

주요 매개변수 설명
start : 시작 값
stop : 끝 값
num : 생성할 값의 개수 (기본값 50)
endpoint : True이면 stop 값을 포함, False이면 stop 값을 포함하지 않음
retstep : True로 설정하면 생성된 배열과 간격(step)을 함께 반환
dtype : 데이터 타입 지정

In [1]:
import numpy as np

# 0에서 1까지 5개의 값 생성 (끝 값 포함)
arr1 = np.linspace(0, 1, 5)

In [2]:
arr1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# np.random.randn() 문법
np.random.randn()는 정규분포(가우시안 분포)를 따르는 난수를 생성하는 함수입니다.

numpy.random.randn(d0, d1, ..., dn)

## 주요 특징
###### 분포: 평균(mean) = 0, 표준편차(std) = 1인 표준 정규분포에서 난수를 생성합니다.
###### 매개변수: d0, d1, ..., dn은 배열의 크기를 지정합니다.

###### 예: np.random.randn(3, 2) → (3행, 2열) 배열 생성

###### 반환값: 지정된 크기의 ndarray를 반환하며, 각 원소는 독립적으로 표준 정규분포에서 뽑은 값입니다.

In [ ]:
import numpy as np

# 1개의 난수 생성 (스칼라 값)
x = np.random.randn()
print(x)  

# 5개의 난수 생성 (1차원 배열)
arr1 = np.random.randn(5)
print(arr1) 
# 2차원 배열 (3행 2열)
arr2 = np.random.randn(3, 2)
print(arr2)

0.6460007307251222
[ 0.08511772  0.11390606  0.86459251  0.67781719 -1.86256997]
[[-0.66917363 -0.26376938]
 [-0.12587019  0.38022937]
 [ 1.14837614 -1.65470366]]
